version: '3.5'

services:
  om-api:
    build:
      context: .
      dockerfile: dockerbits/openmoney-api/Dockerfile
    # ports:
    #   - 8080:80
    # volumes:
    #   - ./dockerbits/openmoney-api/entrypoint.sh:/opt/om/entrypoint.sh
    #   - ./openmoney-api:/opt/om
    environment:
      OM_ENV: dev
      ROOT_SPACE: cc
      ROOT_CURRENCY: cc
      COUCHBASE_ADMIN_USERNAME: admin
      COUCHBASE_ADMIN_PASSWORD: asdfasdf
      COUCHBASE_LO: couchbase
      # COUCHBASE_INIT_WAIT: 15
      ADMIN_USERNAME: omadmin
      ADMIN_PASSWORD: ompass
      ADMIN_EMAIL: om@localhost.com
      PORT: 80

  om-ui:
    build:
      context: .
      dockerfile: dockerbits/openmoney-network/Dockerfile
    ports:
      - 8888:80

  couchbase:
    image: couchbase:community-6.5.0
    # ports:
    #   - 8091:8091
